require_relative './rps/commands.rb'
require_relative './rps/games.rb'
require_relative './rps/db.rb'
require_relative './rps/invites.rb'
require_relative './rps/matches.rb'
require_relative './rps/sessions.rb'
require_relative './rps/users.rb'
